### ISSUE TITLE
Remove color module

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/researchdata#160]
It is deprecated, and we don't use it.

[Deprecation notice](https://www.drupal.org/docs/core-modules-and-themes/deprecated-and-obsolete-modules-and-themes#s-color)

- [ ] Turn off the module in the UI locally
- [ ] Delete the code for this module from the repo
- [ ] Test locally to make sure the site is still working as expected
- [ ] In staging: turn off the module in the UI (or perhaps the YAML configuration files can do this work for us?)
- [ ] Deploy your branch to staging
- [ ] In prod: turn off the module in the UI
- [ ] Deploy your branch to staging

**Comment by sandbergja** [comment]
Check if we can remove it, or if we need to keep it (to allow users to customize colors)

**Comment by kevinreiss** [comment]
uninstalled through the admin UI in production.
