### ISSUE TITLE
Readme.md is overwritten by core updates

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/researchdata#163]
Should this information reside elsewhere? Every time a core update is run this file is overwritten. Could we move the info to another file that won't be reset update a core update, but still displays as the default readme for a github project.

**Comment by sandbergja** [comment]
I wonder if this could prevent drupal from overwriting the readme: https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_6

**Comment by rladdusaw** [comment]
GitHub will prioritize a readme file located in the .github folder of a project.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes

**Comment by carolyncole** [comment]
The instructions here: https://github.com/pulibrary/researchdata/wiki/Upgrade-Drupal-core-via-Composer Indicate in step 4 to drop the changes.
