### ISSUE TITLE
Events and Workshops are not displaying on homepage and Training and Events page

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/researchdata#219]
- Trainings are not displaying on the PRDS home page (displaying dates but no links or other details)

![Screenshot of Trainings list with only dates and no other details](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/1479ec4c-7d8b-47c0-b331-650ca6c98565)

- Events in LibCal are not showing up under workshops on the PRDS Training and Events page (displaying some dates but no links or additional info)

![screenshot of un-populated Workshops section of Training and Events page](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/bab3e90e-e444-46e5-8885-c85b5b1c9283)

### Implementation notes:
- Investigate whether there is an issue with the lib_jobs event feed (see https://github.com/pulibrary/lib_jobs/issues/415 for original implementation)

**Comment by kevinreiss** [comment]
The issue appears to that all the entries that are blank do not have a "Location" field value. The Drupal views that display the list in both places require that field, because the html template that builds the display for the linkable entry in the list is stored in the "rewrite results" configuration option for that field in the view.

**Comment by kevinreiss** [comment]
We are actually imported libcal RSS for this site. Configuration is here: https://github.com/pulibrary/researchdata/blob/9cb10e956bcb603e3f733fa33c40f10b69e70a00/sites/default/config/migrate_plus.migration.event_rss_importer.yml#L50

It appears we need the libcal:location element to be populated.

**Comment by kevinreiss** [comment]
Resolved, staff know to populate the location when creating an event in libcal.
