### ISSUE TITLE
PRDS website LibCal feed

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/researchdata#247]
See https://github.com/pulibrary/researchdata/issues/244 for details

**Comment by VickieKarasic** [comment]
Also, figure out ways to pull in other groups' workshops onto the PRDS page, and for us to send workshops to others' pages.

**Comment by kevinreiss** [comment]
Does "other groups' workshops" equal feeds that are populated by applying tags to our libcal calendar?

**Comment by VickieKarasic** [comment]
No, this would be adding a feed from other campus event calendars, like My PrincetonU, to display relevant workshops coming up from Research Computing, for example. Alternatively, they could manually input links for upcoming campus workshops of interest but wanted to explore what having a feed to an external calendar on their site might look like. Similarly, they wanted a way to share PRDS workshops with other groups like Research Computing, and I think that could be accomplished either by sharing the RSS feed with the internal tag from LibCal or collating the PRDS workshops into one link with a keyword search or something.

**Comment by VickieKarasic** [comment]
Sounds good - we haven't gotten requests for specific feeds yet, but I will create new tickets if/when we do. And yes, I was thinking we'd share the RSS feed directly from LibCal with the internal tag for "prds" to any outside folks.
