### ISSUE TITLE
Production Environment Reports No image processing Library

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/researchdata#263]
Need to check the role to make sure one is being installed, if it is something else has gone wrong. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0l6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--269252a6ce704c07ebd7ef03275ab3192b9822ea/Screenshot%202023-10-13%20at%208.46.09%20AM.png)

- [x] Check command line image options on the machine for common libraries like GD or Imagemagick
- [ ] Check role to see what is being installed. 

Only production reports this, staging has this installed so this is odd. 

## Impact
This means images users attach will not resize properly if they apply any drupal image style features to the graphic.

**Comment by kevinreiss** [comment]
The php-gd package is what needs to be installed. Doesn't seem to be explicitly part of our php, drupal7, or drupal9 roles though it appears to be installed on all php related boxes except prds-prod1. 

This command tells you if the box has this included in the PHP env. 

```php -i | grep 'GD\|ImageMagick'```

**Comment by sandbergja** [comment]
This is currently blocked by needing to upgrade to jammy.  The [ppa we relied on to install php and its modules](https://launchpad.net/%7Eondrej/+archive/ubuntu/php) no longer supports Ubuntu 18.04.  Fortunately, @kayiwa confirmed that the playbook does install php-gd as expected when run on a jammy box.

**Comment by sandbergja** [comment]
This is currently blocking deploying to prod.  `cap production deploy` gives the following:

```
00:12 drupal:composer_install
      01 cd /var/www/researchdata/releases/20231024211753 && composer install --no-dev
      01 /home/deploy/.bashrc: line 1: /home/deploy/app_configs/*: No such file or directory
      01 Installing dependencies from lock file
      01 Verifying lock file contents can be installed on current platform.
      01 Your lock file does not contain a compatible set of packages. Please run composer update.
      01
      01   Problem 1
      01     - drupal/core is locked to version 10.1.5 and an update of this package was not requested.
      01     - drupal/core 10.1.5 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd…
      01   Problem 2
      01     - drupal/core 10.1.5 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd…
      01     - drupal/seven 1.0.0 requires drupal/core ^9 || ^10 -> satisfiable by drupal/core[10.1.5].
      01     - drupal/seven is locked to version 1.0.0 and an update of this package was not requested.
```

**Comment by sandbergja** [comment]
Closed by https://github.com/pulibrary/princeton_ansible/pull/4437
